# Sistema di produzione di neve artificiale
---

## Formulazione del problema

- orizzonte temporale: $t=0,1,...T$, $T = 72$ ore considerando un time step orario
- stato $x_t: (temperatura\_ora\_t,umidità\_ora\_t,livello\_neve\_ora\_t) = (T_t,RH_t,d_t) = (i,j,k)$
- spazio degli stati $x_t \in X_t=\{(i,j,k): i=1,...,50, j=1,...,50, k=1,...,n\}$
    - $T_t \in\{T_1,...,T_{50}\}_t$ con valori diversi da ora in ora
        - $T_t$ variabile aleatoria discreta con pmf $P(T_t=T_i)_t$
    - $RH_t \in\{RH_1,...,RH_{50}\}_t$ con valori diversi da ora in ora
        - $RH_t$ variabile aleatoria discreta con pmf $P(RH_t=RH_i)_t$
    - $d_t \in D=\{0,...,max_d\}, |D|=n$
- ingresso $u_t=(af_t,wf_t)$
    - $af_t$: flusso di aria iniettato nella macchina sparaneve nell'ora t $[m^3/h]$
    - $wf_t$: flusso di acqua iniettato nella macchina sparaneve nell'ora t $[m^3/h]$
- spazio degli ingressi $u_t \in U= 
    \begin{cases}
    \{(0,0)\} & \text{se } \text{la } \text{neve } \text{non } \text{può } \text{essere } \text{prodotta } \text{dati } (T_t,RH_t) \\
    \{(min_{af},min_{wf}),...,(max_{af},max_{wf})\} & \text{altrimenti } 
    \end{cases}$
    - $min_{wf} = 0.6 [m^3/h], max_{wf} = [3.6,5.4] [m^3/h]$
        - step di discretizzazione: $0.2$
    - $min_{af} = 6 [m^3/h], max_{af} = 27 [m^3/h]$
        - step di dicretizzazione: $1$
    - la neve non può essere prodotta se la temperatura del bulbo umido è superiore alla soglia operativa $T_{wb,soglia} = -2.5 °C$
- matrice di transizione per le componenti di temperatura e umidità dello stato
    - $P((T_{t+1}=i,RH_{t+1}=j)|(T_{t}=i',RH_{t}=j'))=P(T_{t+1}=i|T_t=i')_{t+1}*P(RH_{t+1}=j|RH_t=j')_{t+1}$
- funzione di transizione per la componente "livello_neve" dello stato
    - $d_{t+1}=d_t+Neve\_prodotta(x_t,u_t)-Neve\_fusa(x_t)$
    - valore da approssimare al valore discreto più vicino assunto da $d_t$
- funzione per determinare la neve prodotta in un time step in $m^3$
    - $Neve\_prodotta(T_t,RH_t,af_t,wf_t)=k(T_t,RH_t)*min(af_t,wf_t)$
    - $k=\alpha * max(0,T_{wb,soglia}-T_{wb})$ coefficiente di efficienza
    - $\alpha:$ coefficiente calibrato $\in [0.4,1]$
    - $T_{wb,soglia} = -2.5 °C$: soglia (wet-bulb) operativa del generatore
    - $T_{wb} ≈ T_t ⋅arctan(0.151977⋅(RH_t+8.313659)^{0.5})+arctan(T_t+RH_t)-arctan(RH_t−1.676331)
+0.00391838⋅RH^{1.5}⋅arctan(0.023101⋅RH)−4.686035$
        - dove $T_t$ in $°C$ e $RH_t$ in percentuale
- funzione per determinare la neve fusa in un time step in $m^3$
    - $Neve\_fusa(x_t)= (DDF/(1000*24)) * max(T_{avg}-T_0,0) * A$
        - $DDF = degree-day-factor (mm/°C/giorno)$ (tipicamente 1–10 mm)
        - $T_{avg} = temperatura-media °C$
        - $T_0 = soglia (šC)$
        - $A = area (m^2)$
- stage cost $g(u_t):$ deterministico, tempo-invariante
    - $g(u_t)=prezzo\_energia*(E_{ventola}+E_{compressore}(u_t)+E_{pompa}(u_t))$
    - $prezzo\_energia$ in kWh
    - $E_{ventola}=18.5 kWh$ costante
    - $E_{compressore}(u_t)= e * af_t * 60$
        - $e=6.2 [kW/(m^3/min)]$
        - $af_t [m^3/h]$
    - $E_{pompa}(u_t)=k_{pump}*wf_t$
        - $k_{pump}=3.5 [kWh/m^3]$
        - $af_t [m^3/h]$
- Terminal cost $g_T(x_T)$:
    - $g_T((i,j,k)) = \begin{cases} 0 & \text{if } k = n \\ \infty & \text{if } k \neq n \end{cases}$
    - costo infinito se non viene prodotta $max_d [m^3]$ di neve al termine dell'orizzonte temporale

## Formulazione del problema
---

### Importazione moduli

In [1]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import json
import math 
from functions import *
from numba import njit, prange

### Parametri del problema

In [2]:
n_fasce=24 #fasce orarie
n_T = 30 #numero di intervalli di discretizzazione di temperatura
n_RH = 30 #numero di intervalli di discretizzazione di umidità
n_T_RH = n_T * n_RH #numero di possibili combinazioni di temperatura e umidità per fascia oraria
max_d=50 #profondità massima della neve
step_d=0.5 #step di discretizzazione della profondità della neve
#flusso di aria minimo e massimo in ingresso allo sparaneve
min_af=6
max_af=27
af_step=1 #step di discretizzazione del flusso di aria
#flusso di acqua minimo e massimo in ingresso allo sparaneve
min_wf=0.6
max_wf=4.5 #[3.6,5.4]
wf_step=0.2 #step di discretizzazione del flusso di acqua
d_target=35 #livello di neve che deve essere raggiunta in m^3

### Caricamento dati meteorologici da file

In [3]:
# CARICAMENTO DATI temperatura e umidità DA FILE JSON
with open("pmf_temperature.json", "r", encoding="utf-8") as f1:
    temperature = json.load(f1)

with open("pmf_humidity.json", "r", encoding="utf-8") as f2:
    humidity = json.load(f2)

# conversione dei dizionari in liste
#temperatura
temp_val=np.empty((n_fasce,n_T)) #valori discreti per fasce orarie
temp_pmf=np.empty((n_fasce,n_T)) #pmf per fasce orarie
f=0
for fasce,dict_val in temperature.items():
    temp_val[f]=np.array(dict_val['values'],dtype=np.float32)
    temp_pmf[f]=np.array(dict_val['pmf'],dtype=np.float32)
    f+=1
    
#umidità
humid_val=np.empty((n_fasce,n_RH)) #valori discreti per fasce orarie
humid_pmf=np.empty((n_fasce,n_RH)) #pmf per fasce orarie
f=0
for fasce,dict_val in humidity.items():
    humid_val[f]=np.array(dict_val['values'],dtype=np.float32)
    humid_pmf[f]=np.array(dict_val['pmf'],dtype=np.float32)
    f+=1

#caricamento delle matrici delle probabilità condizionate da file
P_T_list = load_transition_matrices("transition_T.json") #lista di matrici P_T, una per ogni fascia oraria
P_RH_list = load_transition_matrices("transition_RH.json") #lista di matrici P_RH, una per ogni fascia oraria

print("Caricate", len(P_T_list), "matrici di transizione T")
print("Caricate", len(P_RH_list), "matrici di transizione RH")
#print("Dimensione prima matrice T:", P_T_list[0].shape)
#print(P_T_list[0])

Caricate 24 matrici di transizione T
Caricate 24 matrici di transizione RH


### Formulazione del problema 

In [4]:
# Definizione dello spazio dei valori discreti della profondità della neve
depth_space=np.arange(0,max_d+step_d,step_d,dtype=np.float32)
n_d=depth_space.shape[0] ##numero di intervalli di discretizzazione della profondità della neve

# Spazio degli stati
state_space=np.empty((n_fasce,n_T,n_RH,n_d,3))
n_states=n_T*n_RH*n_d #numero di stati per fascia oraria
# - definizione di uno spazio degli stati per ogni fascia oraria
for f in range(n_fasce):
    X=np.empty((n_T,n_RH,n_d,3),dtype=np.float32)
    for i,T in enumerate(temp_val[f]):
        for j,RH in enumerate(humid_val[f]):
            for k,d in enumerate(depth_space):            
                X[i,j,k]=[T,RH,d]
    state_space[f]=X

print(state_space[0].shape)
#print(state_space[0])

# Spazio degli ingressi
af_val=np.arange(min_af,max_af+af_step,af_step,dtype=np.float32)
af_n_val=af_val.shape[0]
wf_val=np.arange(min_wf,max_wf+wf_step,wf_step,dtype=np.float32)
wf_n_val=wf_val.shape[0]
U_default=np.empty((af_n_val*wf_n_val,2),dtype=np.float32)
for i,af in enumerate(af_val):
    for j,wf in enumerate(wf_val):
        U_default[i*wf_n_val+j]=[af,wf]
#U=input_space(-1,90,min_af, max_af, min_wf, max_wf, af_step, wf_step)

# Calcolo matrici P_t di transizione delle componenti temperatura e umidità dello stato
# --> P_list conterrà una matrice di transizione per fascia oraria
P_list = np.empty((n_fasce,n_T_RH,n_T_RH))

for f in range(n_fasce):
    P_T = P_T_list[f] #matrice delle probabilità condizionate della temperatura relativa alla fascia f
    P_RH = P_RH_list[f] #matrice delle probabilità condizionate dell'umidità relativa alla fascia f
    P_list[f]=build_joint_transition(P_T, P_RH)

print(P_list[0].shape)
#print(P_list[0])

# Dinamica del sistema
# - funzione che restituisce uno stato iniziale secondo le distribuzioni di temperatura e umidità nella fascia oraria iniziale
# - e secondo la profondità iniziale della neve passata come parametro
def get_initial_state(f_t0,d0):
    # --> f_t0: fascia oraria dell'istante di tempo iniziale t0 del time horizon
    # da aggiungere il controllo della fascia oraria
    pmf_T_t0=temp_pmf[f_t0] # pmf temperatura nella fascia f_t0
    pmf_RH_t0=humid_pmf[f_t0] # pmf umidità nella fascia f_t0
    T0=np.random.choice(temp_val[f_t0], p=pmf_T_t0) # estrazione di un campione di temperatura dalla relativa pmf
    RH0=np.random.choice(humid_val[f_t0], p=pmf_RH_t0) # estrazione di un campione di umidità dalla relativa pmf
    x_0=np.array([T0,RH0,d0],dtype=np.float32)
    return x_0
print(get_initial_state(0,depth_space[-1]))

# - funzione di transizione per la componente 'profondità_neve' dello stato (deterministica)
@njit
def depth_transition(x_t,u_t):
    T_t=x_t[0]
    RH_t=x_t[1]
    d_t=x_t[2]
    af_t=u_t[0]
    wf_t=u_t[1]
    # profondità della neve al prossimo time step (fascia oraria)
    d_next=d_t+snow_produced(T_t,RH_t,af_t,wf_t)-snow_melted(T_t,RH_t)
    if d_next<0:
        d_next_discretized=np.float32(0)
    else: # arrotondamento al campione discreto più vicino
        d_next_discretized=depth_space[np.argmin(np.abs(depth_space-d_next))]
    return d_next_discretized

x_t=np.array([-13.805833333333334,26.206190154216248,5],dtype=np.float32)
u_t=np.array([10,3],dtype=np.float32)
print(depth_transition(x_t,u_t))

# - evoluzione di uno step per temperatura e umidità, secondo la matrice di transizione realtiva alla fascia f
def weather_transition(x_t,f): #da aggiungere la rotazione delle fasce --> 23 - 0
    T_t=x_t[0]
    RH_t=x_t[1]
    # matrice di transizione relativa alla fascia f
    P_f = P_list[f] 
    # conversione stato in indice
    state_idx = state_to_index(T_t,RH_t,temp_val[f],humid_val[f])
    # estrazione di un campione secondo la pmf condizionata allo stato corrente, presente nella matrice P_f
    next_state_idx = np.random.choice(np.arange(0,n_T_RH,1), p=P_f[state_idx]) 
    # conversione indice ottenuto in stato
    if f<23:
        next_T, next_RH = index_to_state(next_state_idx,temp_val[f+1],humid_val[f+1])
    else: #siamo nell'ultima fascia oraria, i prossimi valori da considerare per temperatura e umidità vengono presi dalla fascia 0
        next_T, next_RH = index_to_state(next_state_idx,temp_val[0],humid_val[0])
    return next_T, next_RH
print(weather_transition(x_t,0))

"""
# - simulazione del sistema per un singolo time horizon t=0,...,T
def simulate(T,d0):
    # --> T: lunghezza time horizon
    # --> d0: profondità della neve all'inizio del time horizon
    X_sim=np.empty((T,3)) #lista degli stati visitati dal sistema durante la simulazione
    f_t0=0 #fascia oraria a cui appartiene t0
    x_0=get_initial_state(f_t0,d0) 
    # inizializzazione
    u_t=np.array([0,0],dtype=np.float32)
    x_t=x_0
    f_t=f_t0
    # iterazione
    for t in range(T):
        next_T, next_RH = weather_transition(x_t,f_t)
        next_d = depth_transition(x_t,u_t)
        x_tp1 = np.array([next_T,next_RH,next_d],dtype=np.float32)
        X_sim[t]=x_tp1
        print("time "+str(t)+", fascia "+str(f_t)+", stato: "+str(x_tp1))
        x_t=x_tp1
        f_t=(t+1)%24

simulate(72,depth_space[-1])
"""
@njit
def stage_cost(x_t,u_t):
    T_t=x_t[0]
    RH_t=x_t[1]
    af_t=u_t[0]
    wf_t=u_t[1]
    energy_price=0.25 #€/kWh
    E_fan=18.5 #kWh
    e=6.2 #kW/(m^3/min)
    E_compressor=e*af_t #kWh
    k_pump=2.7 #kWh/m^3 ~0.2–2.7 kWh/m³
    E_pump=k_pump*wf_t #kWh 
    return energy_price*(E_fan+E_compressor+E_pump)

@njit
def terminal_cost(x_T):
    d_t=x_T[2]
    if d_t!=d_target:
        return np.inf
    else:
        return 0

(30, 30, 101, 3)
(900, 900)
[-1.9908333 43.978912  50.       ]
30.0
(-13.4375, 29.863018035888672)
time 0, fascia 0, stato: [-8.8595  87.37928 50.     ]
time 1, fascia 1, stato: [-9.75375 87.82011 50.     ]
time 2, fascia 2, stato: [-10.317708  89.604     50.      ]
time 3, fascia 3, stato: [-8.565666 89.04641  50.      ]
time 4, fascia 4, stato: [-8.746   89.13891 50.     ]
time 5, fascia 5, stato: [-9.473125 89.16512  50.      ]
time 6, fascia 6, stato: [-9.1575  90.39367 50.     ]
time 7, fascia 7, stato: [-7.5885415 92.221436  50.       ]
time 8, fascia 8, stato: [-5.91575 92.11445 50.     ]
time 9, fascia 9, stato: [-4.91225 91.53838 50.     ]
time 10, fascia 10, stato: [-4.5325   82.207535 50.      ]
time 11, fascia 11, stato: [-3.836875 78.53323  50.      ]
time 12, fascia 12, stato: [-5.096   78.25273 50.     ]
time 13, fascia 13, stato: [-5.5794168 72.927605  50.       ]
time 14, fascia 14, stato: [-6.889583 76.35178  50.      ]
time 15, fascia 15, stato: [-7.553125 85.06775  

In [5]:
print(temp_val[0][np.argmin(np.abs(temp_val[0]-(10)))])


7.461166858673096


In [6]:
print(temp_val[0])

[-15.38116646 -14.59350014 -13.80583286 -13.01816654 -12.23050022
 -11.44283295 -10.65516663  -9.86750031  -9.07983303  -8.29216671
  -7.50449991  -6.71683311  -5.92916679  -5.1415      -4.3538332
  -3.56616664  -2.77850008  -1.99083328  -1.20316672  -0.41549999
   0.37216666   1.15983331   1.94749999   2.73516655   3.52283335
   4.31050014   5.09816647   5.88583326   6.67350006   7.46116686]


In [7]:
print(stage_cost(np.array([temp_val[0][15],humid_val[0][25]],dtype=np.float32),np.array([10,2.5],dtype=np.float32)))

21.8125


In [8]:
U_t=input_space(temp_val[0][15],humid_val[0][25],U_default)
#print(U_t)
print(depth_transition(np.array([temp_val[0][15],humid_val[0][25],depth_space[0]],dtype=np.float32),np.array([10,2.5],dtype=np.float32)))

3.5


In [9]:
print(temp_val[0][15])
print(humid_val[0][25])

-3.566166639328003
87.1412353515625


### Implementazione algoritmo DP
---

In [10]:
@njit
def argmin(T_idx,RH_idx,d_idx,t,f_t):
    [T,RH,d]=state_space[f_t][T_idx,RH_idx,d_idx]
    U_t=input_space(T,RH,U_default)
    E_values=np.zeros(len(U_t))
    for u_idx,u in enumerate(U_t):
        E_values[u_idx]=stage_cost([T,RH,d],u)+expected_cost_to_go(T,RH,d,u,t,f_t)
    index=np.argmin(E_values)
    return U_t[index]

@njit
def expected_cost_to_go(T,RH,d,u,t,f_t):
    d_next=depth_transition([T,RH,d],u)
    k=np.where(depth_space == d_next)[0][0]
    E_cost_to_go=0
    if f_t==23: f_t_next=0
    else: f_t_next=f_t+1
    for T_idx in range(n_T):
        for RH_idx in range(n_RH):
            T_next=temp_val[f_t_next][T_idx]
            RH_next=humid_val[f_t_next][RH_idx]
            E_cost_to_go+=V_list[t+1][i,j,k]*P_list[f_t][state_to_index(T,RH,temp_val[f_t],humid_val[f_t]),state_to_index(T_next,RH_next,temp_val[f_t_next],humid_val[f_t_next])]
    return E_cost_to_go

T=72 #lunghezza time horizon in ore
n_days=72//24 #lunghezza time horizon in giorni
V_list=np.zeros((T+1,n_T,n_RH,n_d),dtype=np.float32) #lista di cost value functions, una per ogni istenate di tempo
mu_star_list=np.zeros((T,n_T,n_RH,n_d,2),dtype=np.float32)# policy da trovare, per ogni fascia oraria
print(V_list[0].shape)
print(mu_star_list[0].shape)

# INIZIALIZZAZIONE
# loop over all the possible states
target_d_idx=np.where(depth_space == 50)[0][0] #indice di profondità da raggiungere
for i in range(n_T):
    for j in range(n_RH):
        for k in range(n_d): 
            if k<target_d_idx:
                V_list[T][i,j,k]=1e12

"""
@njit(parallel=True)
def dp_step(t,f_t,V_list,mu_star_list,temp_curr,humid_curr,depth_space,temp_next,humid_next,P_matrix_current,U_default):
    # loop over all the states 
    
    for i in prange(n_T):
        print(f"temperatura {i}")
        for j in range(n_RH):
            for k in range(n_d):  
                T=temp_curr[i]
                RH=humid_curr[j]
                d=depth_space[k]
                x_t = np.array([T, RH, d], dtype=np.float32)
                # CALCOLO ARGMIN
                U_t=input_space(T,RH,U_default)
                E_values=np.zeros(len(U_t))
                for u_idx in range(len(U_t)):
                    u=U_t[u_idx]
                    E_values[u_idx]=stage_cost(x_t,u)+expected_cost_to_go(T,RH,d,u,t,f_t)
                index=np.argmin(E_values)
                mu_star_list[t,i,j,k]=U_t[index]
                # CALCOLO EXPECTED COST TO GO
                d_next=depth_transition(x_t,mu_star_list[t,i,j,k])
                k_next=np.searchsorted(depth_space, d_next)
                E_cost_to_go=0
                idx_curr_weather = i * n_RH + j
                for i_next in range(n_T):
                    for j_next in range(n_RH):
                        idx_next_weather = i_next * n_RH + j_next
                        prob=P_matrix_current[idx_curr_weather,idx_next_weather]
                        if prob>0:
                            E_cost_to_go+=V_list[t+1,i_next,j_next,k_next]*prob
                V_list[t,i,j,k]=stage_cost(x_t,mu_star_list[t,i,j,k])+E_cost_to_go
"""
@njit(parallel=True)
def dp_step(t, f_t, V_list, mu_star_list, temp_curr, humid_curr, depth_space, temp_next, humid_next, P_matrix_current, U_default):
    
    # Dimensioni
    n_T = len(temp_curr)
    n_RH = len(humid_curr)
    n_d = len(depth_space)
    
    n_T_next = len(temp_next)
    n_RH_next = len(humid_next)
    
    # Loop Parallelo sugli stati (Temperatura)
    for i in prange(n_T):
        for j in range(n_RH):
            for k in range(n_d):
                
                # --- 1. Definizione dello Stato Corrente ---
                T = temp_curr[i]
                RH = humid_curr[j]
                d = depth_space[k]
                
                # Creiamo l'array x_t per le funzioni helper (stage_cost, transition)
                x_t = np.array([T, RH, d], dtype=np.float32)
                
                # --- 2. Recupero Input Ammissibili ---
                # Usiamo la tua input_space (che ora deve ritornare un array 2D corretto)
                U_valid = input_space(T, RH, U_default)
                n_inputs = len(U_valid)
                
                # Variabili per trovare il minimo (logica argmin)
                best_total_cost = np.inf
                best_u = np.zeros(2, dtype=np.float32) # Placeholder
                
                # Indice linearizzato per la matrice P (meteo corrente)
                # Assumiamo che P sia organizzata: righe=stato_corrente, col=stato_next
                idx_curr_weather = i * n_RH + j 
                
                # --- 3. Loop sulle Azioni (u) ---
                for u_idx in range(n_inputs):
                    u = U_valid[u_idx]
                    
                    # A. Costo dello stadio corrente
                    cost_stage = stage_cost(x_t, u)
                    
                    # Se l'input è invalido (costo altissimo), saltiamo i calcoli pesanti
                    if cost_stage >= 1e10: 
                        continue

                    # B. Calcolo dinamico di E_cost_to_go (la variabile che volevi)
                    d_next = depth_transition(x_t, u)
                    
                    # Trova indice k_next (Searchsorted è O(log N), molto veloce)
                    k_next = np.searchsorted(depth_space, d_next)
                    
                    # Clipping indici per sicurezza
                    if k_next >= n_d: k_next = n_d - 1
                    if k_next < 0: k_next = 0
                    
                    # Calcolo del valore atteso iterando sui meteo futuri
                    E_cost_to_go = 0.0
                    
                    for i_next in range(n_T_next):
                        for j_next in range(n_RH_next):
                            
                            # Indice linearizzato meteo futuro
                            idx_next_weather = i_next * n_RH_next + j_next
                            
                            # Accesso diretto alla probabilità
                            prob = P_matrix_current[idx_curr_weather, idx_next_weather]
                            
                            if prob > 1e-8: # Piccola ottimizzazione per zeri
                                val_next = V_list[t+1, i_next, j_next, k_next]
                                E_cost_to_go += prob * val_next
                    
                    # C. Totale e Aggiornamento Minimo
                    total_val = cost_stage + E_cost_to_go
                    
                    if total_val < best_total_cost:
                        best_total_cost = total_val
                        best_u = u # Copia i valori perché u è un array numpy piccolo
                
                # --- 4. Salvataggio Risultati ---
                V_list[t, i, j, k] = best_total_cost
                mu_star_list[t, i, j, k, 0] = best_u[0]
                mu_star_list[t, i, j, k, 1] = best_u[1]


# ITERAZIONI
for t in range(T-1,-1,-1): # loop over all the time instants in [T-1,...,0]
    print(f"Processing time {t}")
    f_t=t%24 #fascia a cui appartiene l'istante t
    # Determina array meteo corrente e prossimo
    temp_curr = temp_val[f_t]
    humid_curr = humid_val[f_t]
    # Se siamo all'ultima ora, il "next" è l'ora 0 (come da tua logica else)
    if f_t == 23: f_t_next=0
    else: f_t_next=f_t+1
    temp_next = temp_val[f_t_next]
    humid_next = humid_val[f_t_next]
    dp_step(t,f_t,V_list,mu_star_list,temp_curr,humid_curr,depth_space,temp_next,humid_next,P_list[f_t],U_default)
    


(30, 30, 101)
(30, 30, 101, 2)
Processing time 71
Processing time 70
Processing time 69
Processing time 68
Processing time 67
Processing time 66
Processing time 65
Processing time 64
Processing time 63
Processing time 62
Processing time 61
Processing time 60
Processing time 59
Processing time 58
Processing time 57
Processing time 56
Processing time 55
Processing time 54
Processing time 53
Processing time 52
Processing time 51
Processing time 50
Processing time 49
Processing time 48
Processing time 47
Processing time 46
Processing time 45
Processing time 44
Processing time 43
Processing time 42
Processing time 41
Processing time 40
Processing time 39
Processing time 38
Processing time 37
Processing time 36
Processing time 35
Processing time 34
Processing time 33
Processing time 32
Processing time 31
Processing time 30
Processing time 29
Processing time 28
Processing time 27
Processing time 26
Processing time 25
Processing time 24
Processing time 23
Processing time 22
Processing time 21


In [11]:
"""
T=72 #lunghezza time horizon in ore
V_list=[np.zeros((n_T,n_RH,n_d),dtype=np.float32) for _ in range(T+1)] #lista di cost value functions, una per ogni istenate di tempo
mu_star_list=[np.zeros((n_T,n_RH,n_d,2),dtype=np.float32) for _ in range(T)] # policy da trovare, per ogni fascia oraria
print(V_list[0].shape)
print(mu_star_list[0].shape)

def dp_step():
    f_t=t%24 #fascia a cui appartiene l'istante t
    for i,T in enumerate(temp_val[f_t]):
        for j,RH in enumerate(humid_val[f_t]):
            for k,d in enumerate(depth_space):
                # CALCOLO ARGMIN
                # - calcolo input space
                wb_temp=T * math.atan(0.151977 * math.sqrt(RH + 8.313659)) + math.atan(T + RH) + -math.atan(RH - 1.676331) + 0.00391838 * (RH ** 1.5) * math.atan(0.023101 * RH) -4.686035
                if wb_temp<=-2.5: #la neve può essere prodotta
                    U_t=U_default
                else:
                    U_t=np.array([0,0],dtype=np.float32)
                E_values=np.zeros(len(U_t))
                # - calcolo expected values dello stato corrente
                for u_idx,u in enumerate(U_t):
                    #E_values[u_idx]=stage_cost([T,RH,d],u)+expected_cost_to_go(T,RH,d,u,t,f_t)
                    # - calcolo stage cost con stato [T,RH,d] e ingresso u
                    stage_cost= 0.25 * (18.5+(6.2*u_t[0])+(2.7*u_t[1])) #energy_price*(E_fan+(E_compressor)+(E_pump))
                    # - calcolo expected cost_to_go
                    d_next=depth_transition([T,RH,d],u)
                    k=np.where(depth_space == d_next)[0][0]
                    E_cost_to_go=0
                    if f_t==23: f_t_next=0
                    else: f_t_next=f_t+1
                    for i,T_next in enumerate(temp_val[0]):
                        for j,RH_next in enumerate(humid_val[0]):
                            E_cost_to_go+=V_list[t+1][i,j,k]*P_list[f_t][state_to_index(T,RH,temp_val[f_t],humid_val[f_t]),state_to_index(T_next,RH_next,temp_val[f_t_next],humid_val[f_t_next])]
                    E_values[u_idx]=stage_cost+E_cost_to_go
                index=np.argmin(E_values)
"""

"\nT=72 #lunghezza time horizon in ore\nV_list=[np.zeros((n_T,n_RH,n_d),dtype=np.float32) for _ in range(T+1)] #lista di cost value functions, una per ogni istenate di tempo\nmu_star_list=[np.zeros((n_T,n_RH,n_d,2),dtype=np.float32) for _ in range(T)] # policy da trovare, per ogni fascia oraria\nprint(V_list[0].shape)\nprint(mu_star_list[0].shape)\n\ndef dp_step():\n    f_t=t%24 #fascia a cui appartiene l'istante t\n    for i,T in enumerate(temp_val[f_t]):\n        for j,RH in enumerate(humid_val[f_t]):\n            for k,d in enumerate(depth_space):\n                # CALCOLO ARGMIN\n                # - calcolo input space\n                wb_temp=T * math.atan(0.151977 * math.sqrt(RH + 8.313659)) + math.atan(T + RH) + -math.atan(RH - 1.676331) + 0.00391838 * (RH ** 1.5) * math.atan(0.023101 * RH) -4.686035\n                if wb_temp<=-2.5: #la neve può essere prodotta\n                    U_t=U_default\n                else:\n                    U_t=np.array([0,0],dtype=np.float32)\

In [12]:
print(mu_star_list[0,:,:,:,:])

[[[[6.  0.6]
   [6.  0.6]
   [6.  0.6]
   ...
   [6.  0.6]
   [6.  0.6]
   [6.  0.6]]

  [[6.  0.6]
   [6.  0.6]
   [6.  0.6]
   ...
   [6.  0.6]
   [6.  0.6]
   [6.  0.6]]

  [[6.  0.6]
   [6.  0.6]
   [6.  0.6]
   ...
   [6.  0.6]
   [6.  0.6]
   [6.  0.6]]

  ...

  [[6.  0.6]
   [6.  0.6]
   [6.  0.6]
   ...
   [6.  0.6]
   [6.  0.6]
   [6.  0.6]]

  [[6.  0.6]
   [6.  0.6]
   [6.  0.6]
   ...
   [6.  0.6]
   [6.  0.6]
   [6.  0.6]]

  [[6.  0.6]
   [6.  0.6]
   [6.  0.6]
   ...
   [6.  0.6]
   [6.  0.6]
   [6.  0.6]]]


 [[[6.  0.6]
   [6.  0.6]
   [6.  0.6]
   ...
   [6.  0.6]
   [6.  0.6]
   [6.  0.6]]

  [[6.  0.6]
   [6.  0.6]
   [6.  0.6]
   ...
   [6.  0.6]
   [6.  0.6]
   [6.  0.6]]

  [[6.  0.6]
   [6.  0.6]
   [6.  0.6]
   ...
   [6.  0.6]
   [6.  0.6]
   [6.  0.6]]

  ...

  [[6.  0.6]
   [6.  0.6]
   [6.  0.6]
   ...
   [6.  0.6]
   [6.  0.6]
   [6.  0.6]]

  [[6.  0.6]
   [6.  0.6]
   [6.  0.6]
   ...
   [6.  0.6]
   [6.  0.6]
   [6.  0.6]]

  [[6.  0.6]
   [6.  0.6]
 

In [13]:
# - simulazione del sistema per un singolo time horizon t=0,...,T
def simulate_optimal_policy(T,d0):
    # --> T: lunghezza time horizon
    # --> d0: profondità della neve all'inizio del time horizon
    X_sim=np.empty((T,3)) #lista degli stati visitati dal sistema durante la simulazione
    t0=0
    f_t0=t0%24 #fascia oraria a cui appartiene t0
    x_0=get_initial_state(f_t0,d0) 
    # inizializzazione
    T_idx = np.searchsorted(temp_val[f_t0], x_0[0])
    RH_idx = np.searchsorted(humid_val[f_t0], x_0[1])
    d_idx = np.searchsorted(depth_space, x_0[2])
    u_t0=mu_star_list[t0,T_idx,RH_idx,d_idx,:]
    # iterazione
    x_t=x_0
    u_t=u_t0
    f_t=f_t0
    for t in range(T):
        print("time "+str(t)+", fascia "+str(f_t)+", stato: "+str(x_t))
        next_T, next_RH = weather_transition(x_t,f_t)
        next_d = depth_transition(x_t,u_t)
        x_tp1 = np.array([next_T,next_RH,next_d],dtype=np.float32)
        X_sim[t]=x_tp1
        x_t=x_tp1
        f_t=(t+1)%24
        if t<=70:
            print("ingresso: "+str(u_t))
            T_next_idx = np.searchsorted(temp_val[f_t], x_t[0])
            RH_next_idx = np.searchsorted(humid_val[f_t], x_t[1])
            d_next_idx = np.searchsorted(depth_space, x_t[2])
            u_t=mu_star_list[t+1,T_next_idx,RH_next_idx,d_next_idx,:]

simulate_optimal_policy(72,0)

time 0, fascia 0, stato: [-5.1415  94.75811  0.     ]
ingresso: [6.        4.3999996]
time 1, fascia 1, stato: [-5.0445  92.38069 10.     ]
ingresso: [6.  4.6]
time 2, fascia 2, stato: [-4.7359166 90.23805   20.5      ]
ingresso: [6.  4.6]
time 3, fascia 3, stato: [-4.494375 91.648186 30.5     ]
ingresso: [6.        4.3999996]
time 4, fascia 4, stato: [-4.829   93.40548 39.     ]
ingresso: [6.  2.6]
time 5, fascia 5, stato: [-3.79    93.45389 44.5    ]
ingresso: [6. 4.]
time 6, fascia 6, stato: [-2.3350418 91.32397   50.       ]
ingresso: [6.  0.6]
time 7, fascia 7, stato: [-1.7581667 87.94699   50.       ]
ingresso: [6.  0.6]
time 8, fascia 8, stato: [-2.1452084 89.57515   50.       ]
ingresso: [6.  0.6]
time 9, fascia 9, stato: [ 3.58225 89.40706 50.     ]
ingresso: [0. 0.]
time 10, fascia 10, stato: [ 5.42575 77.40495 49.     ]
ingresso: [0. 0.]
time 11, fascia 11, stato: [ 7.1481667 76.46429   47.5      ]
ingresso: [0. 0.]
time 12, fascia 12, stato: [ 6.785208 78.53323  45.5     ]
